#!/bin/bash

#login into private registry
npm login

npm publish ./dist/editor/ --access=public

#logout when finished
npm logout
echo "Published successfully. Use 'npm install @rickzhou/ngx-monaco-editor' in the project you want to use it."
